CREATE TABLE IF NOT EXISTS categories (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE
);

ALTER TABLE todos ADD COLUMN due_date TEXT;
ALTER TABLE todos ADD COLUMN category_id INTEGER REFERENCES categories(id);
